# 트리 구조 기반 챗봇 만들기

In [2]:
!pip install sentence_transformers

import torch
import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer, util
import random

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 KB 3.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 63.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 69.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.3/190.3 KB 24.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 108.6 MB/s eta 0:00:00
  Created wheel for sentence_transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125938 sha256=8f94184ce66e7fb241cf12a0b467272e5444528616e98a9ffd1e4a676a9c855e
  Stored in directory: /root/.cache/pip/wheels/5e/6f/8c/d88aec621f3f542d26fac0342bef5e693335d125f4e54aeffe
Successfully built sentence_transformers


# 역할별 학습 모델 로딩

In [3]:
%cd /content/drive/MyDrive/새싹_인공지능SW교육/프로젝트/새싹_최종프로젝트/tree_chatbot

# 현재 단계별로 학습된 모델이라고 가정

# 의도 분류 모델
model1 = SentenceTransformer('snunlp/KR-SBERT-V40K-klueNLI-augSTS')

# 예약 정보 확인 모델
model2 = SentenceTransformer('snunlp/KR-SBERT-V40K-klueNLI-augSTS')

# 재예약 여부 확인 모델
model3 = SentenceTransformer('snunlp/KR-SBERT-V40K-klueNLI-augSTS')

/content/drive/MyDrive/새싹_인공지능SW교육/프로젝트/새싹_최종프로젝트/tree_chatbot


In [4]:
# CNN_reserve_info (예약 정보) 모델 로딩
!pip install konlpy
from konlpy.tag import Komoran
tokenizer = Komoran()

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 51.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 465.6/465.6 KB 37.0 MB/s eta 0:00:00


In [5]:
import pandas as pd
import tensorflow as tf
from tensorflow.keras import preprocessing
import pickle

class Preprocess:
    def __init__(self, word2index_dic='/content/drive/MyDrive/새싹_인공지능SW교육/프로젝트/새싹_자연어처리프로젝트/love_chatbot_sbert_v2(custom_data)/data/chatbot_dict/chatbot_dict.bin' ,userdic=None): # userdic 인자에는 사용자 정의 사전 파일 경로 입력가능
        # 단어 인덱스 사전 불러오기 추가
        if(word2index_dic != ''):
            f = open(word2index_dic, "rb")
            self.word_index = pickle.load(f)
            f.close()
            print("단어 사전 로드 완료..")
        else:
            self.word_index = None
            print("단어 사전 로드 실패..")

        # 형태소 분석기 초기화
        self.komoran = Komoran(userdic=userdic)

        # 제외할 품사
        # 참조 : https://docs.komoran.kr/firststep/postypes.html
        # 관계언 제거, 기호 제거
        # 어미 제거
        # 접미사 제거
        self.exclusion_tags = [
            'JKS', 'JKC', 'JKG', 'JKO', 'JKB', 'JKV', 'JKQ',
            # 주격조사, 보격조사, 관형격조사, 목적격조사, 부사격조사, 호격조사, 인용격조사
            'JX', 'JC',
            # 보조사, 접속조사
            'SF', 'SP', 'SS', 'SE', 'SO',
            # 마침표,물음표,느낌표(SF), 쉼표,가운뎃점,콜론,빗금(SP), 따옴표,괄호표,줄표(SS), 줄임표(SE), 붙임표(물결,숨김,빠짐)(SO)
            'EP', 'EF', 'EC', 'ETN', 'ETM',
            # 선어말어미, 종결어미, 연결어미, 명사형전성어미, 관형형전성어미
            'XSN', 'XSV', 'XSA'
            # 명사파생접미사, 동사파생접미사, 형용사파생접미사
        ]


    # 형태소 분석기 POS 태거
    def pos(self, sentence):
        return self.komoran.pos(sentence)

    # 불용어 제거 후 필요한 품사 정보만 가져오기
    def get_keywords(self, pos, without_tag=False):
        f = lambda x: x in self.exclusion_tags
        word_list = []
        for p in pos:
            if f(p[1]) is False:
                word_list.append(p if without_tag is False else p[0])
        return word_list

    # 키워드를 단어 인덱스 시퀀스로 변환
    def get_wordidx_sequence(self, keywords):
        if self.word_index is None:
            return []
        w2i = []
        for word in keywords:
            try:
                w2i.append(self.word_index[word])
            except KeyError:
                # 해당 단어가 사전에 없는 경우 OOV 처리
                w2i.append(self.word_index['OOV'])
        return w2i

p = Preprocess(word2index_dic='/content/drive/MyDrive/새싹_인공지능SW교육/프로젝트/새싹_자연어처리프로젝트/love_chatbot_sbert_v2(custom_data)/data/chatbot_dict/chatbot_dict.bin',
               userdic=None)

단어 사전 로드 완료..


In [7]:
import tensorflow as tf
from tensorflow.keras.models import Model, load_model
from tensorflow.keras import preprocessing
import gc

# 의도 분류 모델 모듈
class IntentModel:
    def __init__(self, model_name, preprocess):

        # 의도 클래스별 레이블블
        self.labels = {0: "date/time/num_persons", 1: "date/time", 2: "date/num_persons"}

        # 의도 분류 모델 불러오기
        self.model = load_model(model_name)

        # 챗봇 텍스트 전처리기
        self.p = preprocess

    # 의도 클래스 예측
    def predict_class(self, query):
        # 형태소 분석
        pos = self.p.pos(query)

        # 문장내 키워드 추출(불용어 제거)
        keywords = self.p.get_keywords(pos, without_tag=True)
        sequences = [self.p.get_wordidx_sequence(keywords)]





        # PADDING 최대 길이 설정
        # 단어 시퀀스 벡터 크기
        MAX_SEQ_LEN = 9

        # 패딩처리
        padded_seqs = preprocessing.sequence.pad_sequences(sequences, maxlen=MAX_SEQ_LEN, padding='post')

        predict = self.model.predict(padded_seqs)
        predict_class = tf.math.argmax(predict, axis=1)
        return predict_class.numpy()[0]

In [8]:
%cd /content/drive/MyDrive/새싹_인공지능SW교육/프로젝트/새싹_최종프로젝트/tree_chatbot

# p는 이미 만듬
# p = Preprocess(word2index_dic='../train_tools/dict/chatbot_dict.bin',
#                userdic='../utils/user_dic.tsv')

intent = IntentModel(model_name='./models/CNN_reserve_info/sample_reserve_info_model.h5', preprocess=p)

# query = "내일 오후 2시에 8명 테이블 예약할게요.	"
# predict = intent.predict_class(query)
# predict_label = intent.labels[predict]
# print("="*30)
# print(query)
# print("의도 예측 클래스 : ", predict)
# print("의도 예측 레이블 : ", predict_label)

/content/drive/MyDrive/새싹_인공지능SW교육/프로젝트/새싹_최종프로젝트/tree_chatbot


# 모델별 데이터 로딩

In [9]:
# 의도 분류 모델의 데이터

n1_model_data = pd.read_excel("./data/csv/n1_model_data_embedding.xlsx")
n1_model_data

input         output  \
0  저 예약좀 하려고요  네 예약 도와드리겠습니다   
1   저희 예약하려고요  네 예약 도와드리겠습니다   
2  예약 가능 할까요?  네 예약 도와드리겠습니다   

                                    embedding_vector  
0  [-6.54027820e-01 -6.01004958e-02 -3.40717971e-...  
1  [-1.04122841e+00  1.60902455e-01 -3.09858292e-...  
2  [-0.65177596  0.10946269 -0.15992972  0.325598...

In [10]:
# 예약 정보 확인 모델의 데이터

n2_model_data = pd.read_excel("./data/csv/n2_model_data_embedding.xlsx")
n2_model_data

input              output  \
0   이번주 삼월일일 열두시에 다섯명이요   네 잠시만요 확인해드리겠습니다.   
1  이번주 삼월일일 열두시로 예약해주세요    네 인원 수는 몇 명이신가요?   
2         저희 다섯명 예약해주세요  네 날짜와 시간은 어떻게 되나요?   

                                    embedding_vector  
0  [-4.84221607e-01 -5.11881053e-01  1.03826606e+...  
1  [-7.75972009e-01 -5.03116965e-01  3.82048219e-...  
2  [-1.2913437  -0.3099866   0.37403193  0.282407...

In [11]:
# 재예약 여부 확인 모델의 데이터

n3_model_data = pd.read_excel("./data/csv/n3_model_data_embedding.xlsx")
n3_model_data

input             output  \
0   그럼 그 다음날 예약 가능할까요?  네 잠시만요 확인해드리겠습니다.   
1  그럼 다음주 수요일에 예약 되나요?    확인해드리겠습니다. 잠시만요   

                                    embedding_vector  
0  [-2.56438792e-01 -4.83613431e-01 -2.86509916e-...  
1  [-0.26886544 -1.0467653   0.45512262 -0.233039...

In [12]:
# 의도 분류 모델의 임베딩 데이터

n1_model_embedding_data = torch.load('./data/embedding_data/n1_model_data_embedding_data.pt')
n1_model_embedding_data

tensor([[-0.6540, -0.0601, -0.3407,  ..., -0.2535,  0.0344, -0.4374],
        [-1.0412,  0.1609, -0.3099,  ..., -0.3440,  0.0938,  0.2346],
        [-0.6518,  0.1095, -0.1599,  ...,  0.5224,  0.2592,  0.2592]])

In [13]:
# 예약 정보 확인 모델의  임베딩 데이터

n2_model_embedding_data = torch.load('./data/embedding_data/n2_model_data_embedding_data.pt')
n2_model_embedding_data

tensor([[-0.4842, -0.5119,  1.0383,  ..., -0.3320,  0.7583, -0.0951],
        [-0.7760, -0.5031,  0.3820,  ..., -0.2641,  0.3161, -0.2325],
        [-1.2913, -0.3100,  0.3740,  ..., -0.9328,  0.6586,  0.4707]])

In [14]:
# 재예약 여부 확인 모델의 임베딩 데이터

n3_model_embedding_data = torch.load('./data/embedding_data/n3_model_data_embedding_data.pt')
n3_model_embedding_data

tensor([[-0.2564, -0.4836, -0.0287,  ...,  1.1633,  0.0365, -0.0873],
        [-0.2689, -1.0468,  0.4551,  ...,  0.8045, -0.2145,  0.1445]])

# 트리 , 노드 정의

In [16]:
# Getter, Setter 추가
# 클래스 변수 추가

class Tree:
  
  def __init__(self):
    self.root = None

  def set_root(self,node):
    self.root = node

  def get_root(self):
    return self.root

class Node:

  def __init__(self,info):

    # 설명
    self.info = info

    # 각 노드별 역할(task) 구분 키
    # 기본 key = -1
    self.task_key = -1

    # 자식 노드들
    self.children = []

  def get_info(self):
    return self.info

  def set_info(self,new_info):
    self.info = new_info

  def get_task_key(self):
    return self.task_key

  def set_task_key(self,new_key):
    self.task_key = new_key

  def get_children(self):
    return self.children
  
  def set_children(self,*children):
    for child in children:
      self.children.append(child)

  # 각 Node별 역할 
  def task(self,task_key,input,node):
    
    next_node = None

    if task_key == 1:
      next_node = intent_classify(input,node)
    elif task_key == 2:
      next_node = reserve_info_classify(input,node)
    return next_node


# 모델 별 Method

In [28]:
# 예약 정보 확인 task(Method)

def intent_classify(input_intent,node):

  intent_thresholds = 0.7
  idx = -1
  
  sentence = input_intent.replace(" ","")
  sentence_encode = model1.encode(input_intent)
  sentence_tensor = torch.tensor(sentence_encode)

  cos_sim = util.cos_sim(sentence_tensor, n1_model_embedding_data)

  idx+=1
  if cos_sim[0][int(np.argmax(cos_sim))] < intent_thresholds:
    
    print("<System> 의도 분류 : 예약 X \n")

    return node.children[idx]

  else:
    idx+=1
    print("<System> 의도 분류 : 예약 O \n")

    best_sim_idx = int(np.argmax(cos_sim))
    answer = n1_model_data['output'][best_sim_idx]
    
    # print(f'사용자의 질문: {sentence} \n')
    print(f'<System> util.cos_sim 활용 코사인 유사도 : {cos_sim[0][best_sim_idx]}\n')

    print(f"챗봇 : {answer}\n")

    return node.children[idx]

# 노드 역할

In [29]:
# 예약 날짜/인원 확인
# 예약 가능 여부 확인

tree = Tree()

n0 = Node("Node0 : 예약 외의 업무 불가")
n1 = Node("Node1 : 의도 분류 단계")
n2 = Node("Node2 : 예약 정보(날짜/시간/인원) 요청 단계")
n3 = Node("날짜/인원 모두 확인")
n4 = Node("날짜 확인, 인원 미확인 => n2 재요청")
n5 = Node("인원 확인, 날짜 미확인 => n2 재요청")
n6 = Node("예약 가능 여부 체크")
n7 = Node("예약 정보 최종 확인 <종료>")
n8 = Node("예약 불가, 재예약 여부 요청")
n9 = Node("재예약 여부 확인 => n2 재요청")
n10 = Node("예약 취소 확인")

tree.set_root(n1)

# 노드 연결

In [30]:
# 의도: 예약

n1.set_children(n0,n2)
# n1.children.append(n0)
# n1.children.append(n2)

# 예약 정보 확인
n2.set_children(n3,n4,n5)
# n2.children.append(n3)
# n2.children.append(n4)
# n2.children.append(n5)

# 예약 정보 확인 완료 - 예약 가능 여부 확인
n3.set_children(n6)
# n3.children.append(n6)

# 예약 가능 여부 확인
n6.set_children(n7,n8)
# n6.children.append(n7)
# n6.children.append(n8)

# 재예약 여부 확인
n8.set_children(n9,n10)
# n8.children.append(n9)
# n8.children.append(n10)

# 재예약 요청
n9.set_children(n6)
# n9.children.append(n6)

# 사용자 input

In [31]:
# 사용자 통화 시 input 는 STT 잘 받았다고 가정

# input_intent = "저 예약좀 하려고요"
# input_reserve_info = "내일 오후 2시에 8명 테이블 예약할게요."
# input_again_reserve = "그럼 그 다음날 예약 가능할까요?"

# 노드별 task_key 설정

In [32]:
n1.set_task_key(1)

In [33]:
# 전위 호출
def work(node):

  # 현재 Node 출력
  print("<System> " + node.get_info()+"\n")

  # 첫 안내문
  if node == n1:
    print(f"챗봇: 안녕하세요. 신참떡볶이 AI 통화 비서입니다.\n 현재 통화 내용을 보다 더 나은 서비스 개선을 위해 수집될 수 있습니다. \n 무엇을 도와드릴까요? \n")
  
  if node == n0:
    print("챗봇: 현재 예약 이외의 문의는 어렵습니다.\n")

  while node != n7 or node != n10:

    user_input = str(input("사용자 : "))
    print("\n")
    key = node.task_key
    nxt_node = node.task(key,user_input,node)
    work(nxt_node)

  if node == None:
    print("work()가 node 못받음")
  
  # 예약 완료
  if node == n7:
    print("챗봇: 예약이 완료되었습니다. 감사합니다.")
    return

  # 예약 취소
  if node == n10:
    print("챗봇: 다음에 뵙겠습니다. 감사합니다.")
    return

In [34]:
# 사용자 통화 시 input 는 STT 잘 받았다고 가정

# input_intent = "저 예약좀 하려고요"
# input_reserve_info = "이번주 삼월일일 열두시에 다섯명이요"
# input_again_reserve = "그럼 그 다음날 예약 가능할까요?"

In [35]:
work(tree.get_root())

<System> Node1 : 의도 분류 단계

챗봇: 안녕하세요. 신참떡볶이 AI 통화 비서입니다.
 현재 통화 내용을 보다 더 나은 서비스 개선을 위해 수집될 수 있습니다. 
 무엇을 도와드릴까요? 

사용자 : 저 예약좀 하려고요


<System> 의도 분류 : 예약 O 

<System> util.cos_sim 활용 코사인 유사도 : 1.0000001192092896

챗봇 : 네 예약 도와드리겠습니다

<System> Node2 : 예약 정보(날짜/시간/인원) 요청 단계



KeyboardInterrupt: ignored

In [ ]:
gkㅈ